# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
  # TODO This is the Rust channel that build jobs will use by default but can be
  # overridden on a case by case basis down below
    RUST_VERSION: stable

    # TODO Update this to match the name of your project.
    CRATE_NAME: mp3rename

  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  matrix:
    # MinGW
    - TARGET: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: >-
      If ($env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($env:TARGET -eq 'i686-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# TODO This is the "test phase", tweak it as you see fit
test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% &&
      cargo build --target %TARGET% --release &&
      cargo test --target %TARGET% &&
      cargo test --target %TARGET% --release
    )

before_deploy:
  # TODO Update this to build the artifacts that matter to you
  - cargo rustc --target %TARGET% --release --bin %CRATE_NAME% -- -C lto
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  # TODO update `auth_token.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it. Go to https://ci.appveyor.com/tools/encrypt
  # - Paste the output down here
  auth_token:
    secure: 6bNDICA4kZa+GrFNwEte29PEOo2ztShBZP3TVBbYrbxn78j10pEVjA4oFS+wKaLvyB6sF1iVMW6fEtW/7e95gv4q7k4qhU7TNAhulU7xnYrkDgyqZTt3gGveI/VDT0EO+BWBMmtBGmiFsGtmkJazGI8rJwF7b3VxCB+lO1REvosQR5Nw7clgxu5vtbsEPK87lp6H2rWY55jxmUwqhhNLK9IF5A8kcfjbTRy1SqoR+hyXn3DHs9GF3Sa/+r6G8K8VhW4G4BUdIeWylk28muluRc0j3RqCBr2xmuVNCs94YMYyukC8aXtnOzqcXZlaafWTgi8nk3d7W7eYZsiJE8WLLobElClXRI+lCePsXngrjWg8KO1KEvIPVyPswWKpkY8qPJIrSNIGYhY8iDeLYtTKj2qkVJ2cCZMM6/vrOoOvZW1DeBRwpVCAkc2olywid1kUeJ7LQcgABl/CrwttLYa6MXoh82/QQOeDvM4zcPQosHVU7b5/m/J5t0yPf5/PscbZd1zV0Jsl29b5kFMvjv6nbL9E0w0h9S9yv+DKuchRJgf1wZdOMc/ZWevnp1Es54P8lxwmmAFn9KTdEaE8TVkTXtlgTw+4RfwYQgScZsO0GMtsf1zt2SIPdRmU2dGZfK0wJY0Agmzxnh7ChU4mOcRjsp7EOwCHzBfXyav9poyKDlE=
  description: ''
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
