[package]
name = "mp3rename"
version = "1.0.12-pre"
authors = ["Michael Kaaden <github@kaaden.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.2.7182"
clap = "2.33.3"
regex = "1"
walkdir = "2"
